name: Backend CI

on:
  push:
    branches: main
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"
  pull_request:
    branches: main
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - run: |
        pip install -r requirements.txt dev-requirements.txt

      - name: Check code formatting with black
        run: black --check app

      - name: Check for code errors
        run: ruff .

  smoketests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend
          tags: backend_backend
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Execute smoke tests
        run: |
          docker compose --env-file .env.ci up --no-build -d
          bash tests/run_tests.sh
